dir: ./
armoredPubKey: |
  -----BEGIN PGP PUBLIC KEY BLOCK-----

  xjMEAAAAABYJKwYBBAHaRw8BAQdAKvuzjPDqMItpm41NhR7/q/A8cYGjys0X
  e0tZQFT4DeTNGnRlc3QgKG5haCkgPHRlc3RAdGVzdC5jb20+wowEEBYKAD4F
  ggAAAAAECwkHCAmQ3rIjyqxV4tsDFQgKBBYAAgECGQECmwMCHgEWIQS/1XDS
  j72QNxZEWQvesiPKrFXi2wAA3WYA/2eD+s2845j3ObFEKnfBlE+rZAFQ0wEV
  7UmRW/KRAClmAQDX88bGZHAvnpWbDMkr2GQ2hRdMSNWZxKFPszBuTCa/A844
  BAAAAAASCisGAQQBl1UBBQEBB0DQjTqFdVSwgVVnBR5DUEVksQ1Me3vchxZ3
  a0XW7Ix3RgMBCAfCeAQYFggAKgWCAAAAAAmQ3rIjyqxV4tsCmwwWIQS/1XDS
  j72QNxZEWQvesiPKrFXi2wAAhrsA+gJqdHoUas5ebt/lzsvYgwuRwSfxcVb/
  NS6Bkq+NWFgWAQCOekZA0rsubjbxFeJ3tG5xBWu5OHWenjRuFJSQrcynBg==
  =AYei
  -----END PGP PUBLIC KEY BLOCK-----